name: video_stream_example
description: Demonstrates how to use the video_stream plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_stream:
    path: ../

  cupertino_icons: ^1.0.3
  video_player: ^2.1.10
  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
