name: rtmp_camera
description: A new Flutter package to live stream video to RTMP server.
version: 0.0.1
homepage: https://github.com/tatazaza/rtmp_camera

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.0.1+1
  stream_transform: ^2.0.0

dev_dependencies:
  path_provider: ^2.0.9
  camera_platform_interface: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.rtmp_camera
        pluginClass: VideoStreamPlugin
      ios:
        pluginClass: VideoStreamPlugin
